export const htsCmds = {
  HTS_TRADE_INFO_REQUESTED: 'HTS_TRADE_INFO_REQUESTED' as const,
  HTS_TRADE_INFO_SUCCESS: 'HTS_TRADE_INFO_SUCCESS' as const,
  HTS_TRADE_INFO_FAILED: 'HTS_TRADE_INFO_FAILED' as const,

  HTS_TRADE_ORDER_REQUESTED: 'HTS_TRADE_ORDER_REQUESTED' as const,
  HTS_TRADE_ORDER_SUCCESS: 'HTS_TRADE_ORDER_SUCCESS' as const,
  HTS_TRADE_ORDER_FAILED: 'HTS_TRADE_ORDER_FAILED' as const,

  HTS_API_KEY_REQUESTED: 'HTS_API_KEY_REQUESTED' as const,
  HTS_API_KEY_SUCCESS: 'HTS_API_KEY_SUCCESS' as const,
  HTS_API_KEY_FAILED: 'HTS_API_KEY_FAILED' as const,
  HTS_API_KEY_RESET: 'HTS_API_KEY_RESET' as const,
  HTS_API_KEY_STATE_CHANGE: 'HTS_API_KEY_STATE_CHANGE' as const,

  HTS_MARKET_INFO_REQUESTED: 'HTS_MARKET_INFO_REQUESTED' as const,
  HTS_MARKET_INFO_SUCCESS: 'HTS_MARKET_INFO_SUCCESS' as const,
  HTS_MARKET_INFO_FAILED: 'HTS_MARKET_INFO_FAILED' as const,

  HTS_MONEYTRAY_UNIT_CHANGE: 'HTS_MONEYTRAY_UNIT_CHANGE' as const,

  HTS_STD_UNIT_CHANGE: 'HTS_STD_UNIT_CHANGE' as const,

  HTS_ASSETS_REQUESTED: 'HTS_ASSETS_REQUESTED' as const,
  HTS_ASSETS_SUCCESS: 'HTS_ASSETS_SUCCESS' as const,
  HTS_ASSETS_FAILED: 'HTS_ASSETS_FAILED' as const,

  HTS_EXCHANGE_UPDATE: 'HTS_EXCHANGE_UPDATE' as const,

  HTS_MANAGES_REQUESTED: 'HTS_MANAGES_REQUESTED' as const,
  HTS_MANAGES_SUCCESS: 'HTS_MANAGES_SUCCESS' as const,
  HTS_MANAGES_FAILED: 'HTS_MANAGES_FAILED' as const
}
