export const signCmds = {
  MAIL_VALUE_CHANGE_REQUESTED: 'MAIL_VALUE_CHANGE_REQUESTED' as const,
  NAME_VALUE_CHANGE_REQUESTED: 'NAME_VALUE_CHANGE_REQUESTED' as const,
  PWD_VALUE_CHANGE_REQUESTED: 'PWD_VALUE_CHANGE_REQUESTED' as const,
  PWD_CHECK_VALUE_CHANGE_REQUESTED: 'PWD_CHECK_VALUE_CHANGE_REQUESTED' as const,

  SIGN_UP_REQUESTED: 'SIGN_UP_REQUESTED' as const,
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS' as const,
  SIGN_UP_FAILED: 'SIGN_UP_FAILED' as const,
  SIGN_UP_RESET: 'SIGN_UP_RESET' as const,

  MAIL_DUPLICATION_CHECK_SUCCESS: 'MAIL_DUPLICATION_CHECK_SUCCESS' as const,
  MAIL_DUPLICATION_CHECK_FAILED: 'MAIL_DUPLICATION_CHECK_FAILED' as const,

  SIGN_IN_REQUESTED: 'SIGN_IN_REQUESTED' as const,
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS' as const,
  SIGN_IN_FAILED: 'SIGN_IN_FAILED' as const,

  SIGN_REDUCER_RESET: 'SIGN_REDUCER_RESET' as const,

  SIGN_MEMBER_CHECK_REQUESTED: 'SIGN_MEMBER_CHECK_REQUESTED' as const,
  SIGN_MEMBER_CHECK_SUCCESS: 'SIGN_MEMBER_CHECK_SUCCESS' as const,
  SIGN_MEMBER_CHECK_FAILED: 'SIGN_MEMBER_CHECK_FAILED' as const
}
